slogan: Pour les gommes Ã  air de tous types et types de bois, de faisceaux fins de carrosserie et de faisceaux de panneau de verre d'acier inoxydable et d'aluminium.
email: info@straalatelier.com
phone: "+32478766843"
adrStreet: Vijfkruisenstraat 11a
adrPostcode: B-3770
adrCity: Val-Meer
adrLocality: RIEMST
adrCountry: BELGIQUE
images:
  - /showcase/IMG_20201108_170139.jpg
  - /showcase/kabien1.jpg
  - /showcase/Parelstralen.jpg
