slogan: Voor het Luchtgommen van alle soorten en types hout, het Fijnstralen van Carrosserie en Glasparelstralen van Inox en Aluminium.
email: info@straalatelier.com
phone: "+32478766843"
adrStreet: Vijfkruisenstraat 11a
adrPostcode: B-3770
adrCity: Val-Meer
adrLocality: RIEMST
adrCountry: BELGIÃ‹
images:
  - /showcase/IMG_20201108_170139.jpg
  - /showcase/kabien1.jpg
  - /showcase/Parelstralen.jpg
